# Generated by Django 5.0 on 2025-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
    ]
