# Generated by Django 5.0 on 2025-06-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_make_client_fields_nullable'),
    ]

    operations = [
    ]
