# Generated by Django 5.0 on 2025-06-29 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lawyer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Lawyer's full name", max_length=100)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('specialization', models.CharField(choices=[('criminal', 'Criminal Law'), ('civil', 'Civil Law'), ('family', 'Family Law'), ('corporate', 'Corporate Law'), ('real_estate', 'Real Estate Law'), ('immigration', 'Immigration Law'), ('tax', 'Tax Law'), ('employment', 'Employment Law'), ('intellectual_property', 'Intellectual Property Law'), ('general', 'General Practice')], default='general', help_text='Primary area of legal practice', max_length=50)),
                ('bar_number', models.CharField(blank=True, help_text='Bar association number', max_length=50, null=True)),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of legal experience')),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the lawyer is currently accepting new cases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Lawyer',
                'verbose_name_plural': 'Lawyers',
                'ordering': ['name'],
            },
        ),
    ]
